# Use custom format:
format="$directory$git_branch$character"

# Prompt symbols 
[character]
success_symbol = "[ ᐉ](bright-green bold)"
error_symbol = "[ ᐉ](bright-red)"
vicmd_symbol = "[ ᐉ](bright-yellow)"

[directory]
format = "[▉]($style)[(bg:background fg:#48463d) $path ](bg:#48463d fg:#c2bda6)[▕]($style)"
style = "bg:background fg:#48463d"

[git_branch]
format = "[▉]($style)[(bg:background fg:#48463d) \ue725 $branch ](bg:#48463d fg:#c2bda6)[▕]($style)"
style = "bg:background fg:#48463d"